# Generated by Django 3.0.8 on 2020-07-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.CharField(max_length=70)),
                ('title', models.CharField(max_length=70)),
                ('text', models.TextField()),
            ],
        ),
    ]
